<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
  <meta charset="utf-8">
  <meta name="x-apple-disable-message-reformatting">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings xmlns:o="urn:schemas-microsoft-com:office:office">
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <style>
    td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
  </style>
  <![endif]-->

    <title>Welcome Aboard</title>

    <style>/* Your custom CSS resets for email */
/*
 * Here is where you can add your global email CSS resets.
 *
 * We use a custom, email-specific CSS reset, instead
 * of Tailwind's web-optimized base.
*/
body {
  margin: 0;
  width: 100%;
  padding: 0;
  word-break: break-word;
  -webkit-font-smoothing: antialiased
}
img {
  max-width: 100%;
  vertical-align: middle;
  line-height: 100%;
  border: 0
}
/* Tailwind components that are generated by plugins */
/**
 * @import here any custom CSS components - that is, classes that
 * you'd want loaded before the Tailwind utilities, so the
 * utilities can still override them.
*/
/* Tailwind utility classes */
.m-0 {
  margin: 0 !important
}
.my-3 {
  margin-top: 3px !important;
  margin-bottom: 3px !important
}
.my-4 {
  margin-top: 4px !important;
  margin-bottom: 4px !important
}
.mt-6 {
  margin-top: 6px !important
}
.mt-10 {
  margin-top: 10px !important
}
.mb-16 {
  margin-bottom: 16px !important
}
.mb-4 {
  margin-bottom: 4px !important
}
.mb-24 {
  margin-bottom: 24px !important
}
.mr-4 {
  margin-right: 4px !important
}
.ml-1 {
  margin-left: 0.25rem !important
}
.block {
  display: block !important
}
.inline-block {
  display: inline-block !important
}
.flex {
  display: flex !important
}
.table {
  display: table !important
}
.hidden {
  display: none !important
}
.h-4 {
  height: 4px !important
}
.h-px {
  height: 1px !important
}
.h-5 {
  height: 5px !important
}
.h-32 {
  height: 32px !important
}
.h-64 {
  height: 64px !important
}
.h-48 {
  height: 48px !important
}
.min-h-screen {
  min-height: 100vw !important
}
.w-4 {
  width: 4px !important
}
.w-full {
  width: 100% !important
}
.w-14 {
  width: 14px !important
}
.w-5 {
  width: 5px !important
}
.w-600 {
  width: 600px !important
}
.w-48 {
  width: 48px !important
}
.w-1\/2 {
  width: 50% !important
}
.cursor-default {
  cursor: default !important
}
.flex-col {
  flex-direction: column !important
}
.items-center {
  align-items: center !important
}
.justify-center {
  justify-content: center !important
}
.justify-between {
  justify-content: space-between !important
}
.space-y-5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(5px * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(5px * var(--tw-space-y-reverse)) !important
}
.space-y-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(0.25rem * var(--tw-space-y-reverse)) !important
}
.space-x-2 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-x-reverse: 0 !important;
  margin-right: calc(2px * var(--tw-space-x-reverse)) !important;
  margin-left: calc(2px * calc(1 - var(--tw-space-x-reverse))) !important
}
.space-y-4 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(4px * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(4px * var(--tw-space-y-reverse)) !important
}
.overflow-hidden {
  overflow: hidden !important
}
.rounded-md {
  border-radius: 6px !important
}
.rounded {
  border-radius: 4px !important
}
.border {
  border-width: 1px !important
}
.border-gray-300 {
  border-color: #d1d5db !important
}
.border-gray-800 {
  border-color: #1f2937 !important
}
.border-blue-500 {
  border-color: #3b82f6 !important
}
.bg-gray-100 {
  background-color: #f3f4f6 !important
}
.bg-white {
  background-color: #ffffff !important
}
.bg-blue-500 {
  background-color: #3b82f6 !important
}
.bg-gray-400 {
  background-color: #9ca3af !important
}
.bg-indigo-800 {
  background-color: #3730a3 !important
}
.bg-gray-300 {
  background-color: #d1d5db !important
}
.bg-gray-200 {
  background-color: #e5e7eb !important
}
.bg-cover {
  background-size: cover !important
}
.bg-top {
  background-position: top !important
}
.bg-no-repeat {
  background-repeat: no-repeat !important
}
.fill-current {
  fill: currentColor !important
}
.p-1 {
  padding: 0.25rem !important
}
.p-4 {
  padding: 4px !important
}
.p-5 {
  padding: 5px !important
}
.p-48 {
  padding: 48px !important
}
.p-24 {
  padding: 24px !important
}
.py-6 {
  padding-top: 6px !important;
  padding-bottom: 6px !important
}
.px-4 {
  padding-left: 4px !important;
  padding-right: 4px !important
}
.py-2 {
  padding-top: 2px !important;
  padding-bottom: 2px !important
}
.py-16 {
  padding-top: 16px !important;
  padding-bottom: 16px !important
}
.px-24 {
  padding-left: 24px !important;
  padding-right: 24px !important
}
.px-48 {
  padding-left: 48px !important;
  padding-right: 48px !important
}
.py-24 {
  padding-top: 24px !important;
  padding-bottom: 24px !important
}
.py-32 {
  padding-top: 32px !important;
  padding-bottom: 32px !important
}
.pb-32 {
  padding-bottom: 32px !important
}
.pr-16 {
  padding-right: 16px !important
}
.pl-16 {
  padding-left: 16px !important
}
.text-left {
  text-align: left !important
}
.text-center {
  text-align: center !important
}
.font-sans {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important
}
.text-4xl {
  font-size: 36px !important
}
.text-sm {
  font-size: 14px !important
}
.text-2xl {
  font-size: 24px !important
}
.text-lg {
  font-size: 18px !important
}
.text-base {
  font-size: 16px !important
}
.text-xl {
  font-size: 20px !important
}
.text-xs {
  font-size: 12px !important
}
.font-bold {
  font-weight: 700 !important
}
.font-normal {
  font-weight: 400 !important
}
.font-semibold {
  font-weight: 600 !important
}
.font-medium {
  font-weight: 500 !important
}
.uppercase {
  text-transform: uppercase !important
}
.italic {
  font-style: italic !important
}
.leading-64 {
  line-height: 64px !important
}
.leading-24 {
  line-height: 24px !important
}
.leading-full {
  line-height: 100% !important
}
.leading-px {
  line-height: 1px !important
}
.tracking-wider {
  letter-spacing: 0.05em !important
}
.text-white {
  color: #ffffff !important
}
.text-gray-300 {
  color: #d1d5db !important
}
.text-gray-700 {
  color: #374151 !important
}
.text-gray-500 {
  color: #6b7280 !important
}
.text-blue-600 {
  color: #2563eb !important
}
.text-gray-800 {
  color: #1f2937 !important
}
.text-blue-500 {
  color: #3b82f6 !important
}
.text-gray-600 {
  color: #4b5563 !important
}
.underline {
  text-decoration: underline !important
}
.no-underline {
  text-decoration: none !important
}
.transition {
  transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter !important;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1) !important;
  transition-duration: 150ms !important
}
.transition-colors {
  transition-property: background-color, border-color, color, fill, stroke !important;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1) !important;
  transition-duration: 150ms !important
}
.duration-300 {
  transition-duration: 300ms !important
}
.shadow {
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06) !important
}
.shadow-lg {
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05) !important
}
/* Your custom utility classes */
/*
 * Here is where you can define your custom utility classes.
 *
 * We wrap them in the `utilities` @layer directive, so
 * that Tailwind moves them to the correct location.
 *
 * More info:
 * https://tailwindcss.com/docs/functions-and-directives#layer
*/
.hover\:bg-blue-600:hover {
  background-color: #2563eb !important
}
.hover\:bg-gray-800:hover {
  background-color: #1f2937 !important
}
.hover\:bg-blue-500:hover {
  background-color: #3b82f6 !important
}
.hover\:bg-indigo-700:hover {
  background-color: #4338ca !important
}
.hover\:text-blue-400:hover {
  color: #60a5fa !important
}
.hover\:underline:hover {
  text-decoration: underline !important
}
.hover\:no-underline:hover {
  text-decoration: none !important
}
.focus\:border-transparent:focus {
  border-color: transparent !important
}
.focus\:text-blue-800:focus {
  color: #1e40af !important
}
.focus\:outline-none:focus {
  outline: 2px solid transparent !important;
  outline-offset: 2px !important
}
.focus\:ring-offset-0:focus {
  --tw-ring-offset-width: 0px !important
}
.group:hover .group-hover\:text-white {
  color: #ffffff !important
}
@media (max-width: 600px) {
  .sm\:inline-block {
    display: inline-block !important
  }
  .sm\:h-32 {
    height: 32px !important
  }
  .sm\:w-full {
    width: 100% !important
  }
  .sm\:w-16 {
    width: 16px !important
  }
  .sm\:px-16 {
    padding-left: 16px !important;
    padding-right: 16px !important
  }
  .sm\:py-32 {
    padding-top: 32px !important;
    padding-bottom: 32px !important
  }
  .sm\:px-24 {
    padding-left: 24px !important;
    padding-right: 24px !important
  }
  .sm\:px-0 {
    padding-left: 0 !important;
    padding-right: 0 !important
  }
  .sm\:pb-32 {
    padding-bottom: 32px !important
  }
  .sm\:leading-40 {
    line-height: 40px !important
  }
  .sm\:leading-32 {
    line-height: 32px !important
  }
}
</style>

</head>
<body class="bg-gray-100">

    <div class="hidden">We are glad to see your interest in our products. We will keep you posted on the latest&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; </div>
  <div role="article" aria-roledescription="email" aria-label="Welcome Aboard" lang="en">

    <table class="w-full font-sans" cellpadding="0" cellspacing="0" role="presentation">
      <tr>
        <td align="center" class="bg-gray-100">
          <table class="w-600 sm:w-full" cellpadding="0" cellspacing="0" role="presentation">
            <tr>
              <td class="p-48 sm:py-32 sm:px-24 text-center">
                <a target="_blank" href="www.malakoffanalytics.co.ke">
                  <img src="{{asset('images/logo-color.png')}}" width="75" alt="Malakoff Analytics">
                </a>
              </td>
            </tr>
            <tr>
              <td align="center" class="sm:px-24">
                <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                  <tr>
                    <td class="bg-white text-gray-800 text-base text-left p-48 sm:px-24 leading-24 rounded">
                      <p class="text-2xl sm:leading-32 text-gray-700 font-semibold m-0 mb-24 flex">
                        <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="60" height="60" x="0" y="0" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512" xml:space="preserve" class="mr-4"><g><g xmlns="http://www.w3.org/2000/svg"><g><path d="m442 77h-372c-22.091 0-40 17.909-40 40v264h452v-264c0-22.091-17.908-40-40-40z" fill="#ccf5fd" data-original="#ccf5fd"></path><path d="m448 435h-384c-29.823 0-54-24.177-54-54h492c0 29.823-24.176 54-54 54z" fill="#33d8f8" data-original="#33d8f8"></path></g><g><path d="m385.067 301.094-82.331-43.51-3.485 93.056 21.768-18.138 28.001 48.498 37.455-21.625-28-48.498z" fill="#ff6f95" data-original="#ff6f95"></path></g><g><path d="m502 371h-10v-254c0-27.57-22.43-50-50-50h-372c-27.57 0-50 22.43-50 50v254h-10c-5.522 0-10 4.477-10 10 0 35.29 28.71 64 64 64h147c5.522 0 10-4.477 10-10s-4.478-10-10-10h-147c-20.823 0-38.314-14.54-42.854-34h183.103 286.604c-4.539 19.46-22.03 34-42.854 34h-146.999c-5.522 0-10 4.477-10 10s4.478 10 10 10h147c35.29 0 64-28.71 64-64 0-5.523-4.478-10-10-10zm-462-254c0-16.542 13.458-30 30-30h372c16.542 0 30 13.458 30 30v254h-85.66l5.135-2.965c2.297-1.326 3.973-3.51 4.659-6.072.687-2.562.327-5.292-.999-7.588l-22.062-38.214 15.445-5.682c3.705-1.363 6.262-4.778 6.525-8.717.264-3.939-1.814-7.665-5.305-9.509l-82.33-43.509c-3.042-1.608-6.695-1.539-9.673.181-2.979 1.72-4.864 4.849-4.993 8.286l-3.485 93.055c-.147 3.945 2.039 7.608 5.583 9.349 3.543 1.742 7.778 1.235 10.812-1.292l12.645-10.536 13.402 23.213h-127.45-164.249zm309.814 198.876 23.001 39.838-20.135 11.626-23-39.838c-1.475-2.555-4.002-4.328-6.906-4.845-.584-.104-1.171-.155-1.754-.155-2.32 0-4.591.809-6.401 2.317l-4.534 3.778 2.05-54.736 48.427 25.592-5.538 2.038c-2.769 1.019-4.946 3.208-5.95 5.981-1.007 2.774-.734 5.85.74 8.404z" fill="#000000" data-original="#000000"></path><path d="m93.308 126.355h-14.413c-2.655 0-5.202 1.056-7.078 2.936-1.875 1.879-2.927 4.428-2.922 7.083v.062.003 78.617c0 .673.069 1.33.196 1.966.163 2.427 1.195 4.723 2.935 6.444 1.872 1.852 4.399 2.89 7.031 2.89h.075c.085 0 8.577-.065 15.014-.177 24.028-.419 41.469-21.373 41.469-49.822-.001-29.909-17.003-50.002-42.307-50.002zm.488 79.825c-1.521.026-3.159.05-4.773.071-.03-9.466-.093-50.063-.11-59.896h4.396c10.784 0 22.307 7.881 22.307 30-.002 14.656-6.748 29.562-21.82 29.825z" fill="#000000" data-original="#000000"></path><path d="m194.532 206.355h-18v-20h15.936c5.522 0 10-4.477 10-10s-4.478-10-10-10h-15.936v-20h18c5.522 0 10-4.477 10-10s-4.478-10-10-10h-28c-5.522 0-10 4.477-10 10v80c0 5.523 4.478 10 10 10h28c5.522 0 10-4.477 10-10s-4.477-10-10-10z" fill="#000000" data-original="#000000"></path><path d="m235.321 226.221c5.46.901 10.597-2.786 11.498-8.235l6.754-40.842 11.064 40.607c.03.111.062.221.097.331 1.535 4.954 6.004 8.272 11.132 8.272h.057c5.152-.024 9.618-3.393 11.112-8.38.031-.107.062-.215.091-.323l10.682-40.573 7.179 41.001c.851 4.857 5.072 8.277 9.839 8.277.572 0 1.153-.049 1.736-.151 5.44-.953 9.078-6.135 8.126-11.575l-13.755-78.554c-.008-.041-.015-.081-.022-.121-1.006-5.358-5.469-9.299-10.853-9.584-5.373-.271-10.213 3.152-11.776 8.358-.032.109-.063.219-.093.329l-12.459 47.324-12.921-47.42c-.03-.111-.062-.222-.097-.332-1.609-5.192-6.489-8.583-11.852-8.249-5.385.336-9.812 4.322-10.767 9.693-.007.04-.014.079-.021.119l-12.986 78.53c-.899 5.449 2.787 10.597 8.235 11.498z" fill="#000000" data-original="#000000"></path><path d="m393.106 226.355c27.57 0 50-22.43 50-50s-22.43-50-50-50-50 22.43-50 50 22.43 50 50 50zm0-80c16.542 0 30 13.458 30 30s-13.458 30-30 30-30-13.458-30-30 13.458-30 30-30z" fill="#000000" data-original="#000000"></path><circle cx="255.986" cy="435" r="10" fill="#000000" data-original="#000000"></circle></g></g></g></svg>

                          <span class="ml-1"> Your request for a demo has been received.</span>
                      </p>
                      <p class="m-0 mb-24">We are currently processing your request for a demo of our products. <b>Our team will contact
                        you once everything is ready.</b>
                        Thank you for understanding.
                      </p>

                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="py-32">
                            <div class="bg-gray-200 h-px leading-px">&zwnj;</div>
                          </td>
                        </tr>
                      </table>
                      <small class="m-0 mb-16">Not sure why you received this email? Please <a href="mailto:info@malakoffanalytics.co.ke" class="text-blue-500 underline hover:no-underline">let us know</a>.</small>
                      <small class="m-0 mb-16">Thanks, <br>The Malakoff Team</small>
                    </td>
                  </tr>
                  <tr>
                    <td class="h-48"></td>
                  </tr>
                  <tr>
                    <td class="text-center text-gray-600 text-xs px-24">
                      <p class="m-0 mb-4 uppercase">&copy; Malakoff Analytics 2022</p>
                      <p class="m-0 italic">Speed, Convenience, and Accessibility</p>
                      <p class="cursor-default">
                        <a href="www.malakoffanalytics.co.ke" class="text-blue-500 no-underline hover:underline">Site</a> &bull;
                        <a href="#_" class="text-blue-500 no-underline hover:underline">Products</a> &bull;
                        <a href="#_" class="text-blue-500 no-underline hover:underline">Legal</a>
                      </p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

  </div>
</body>
</html>

