<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
  <meta charset="utf-8">
  <meta name="x-apple-disable-message-reformatting">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
  <!--[if mso]>
  <noscript>
    <xml>
      <o:OfficeDocumentSettings xmlns:o="urn:schemas-microsoft-com:office:office">
        <o:PixelsPerInch>96</o:PixelsPerInch>
      </o:OfficeDocumentSettings>
    </xml>
  </noscript>
  <style>
    td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
  </style>
  <![endif]-->

    <title>Welcome Aboard</title>

    <style>/* Your custom CSS resets for email */
/*
 * Here is where you can add your global email CSS resets.
 *
 * We use a custom, email-specific CSS reset, instead
 * of Tailwind's web-optimized base.
*/
body {
  margin: 0;
  width: 100%;
  padding: 0;
  word-break: break-word;
  -webkit-font-smoothing: antialiased
}
img {
  max-width: 100%;
  vertical-align: middle;
  line-height: 100%;
  border: 0
}
/* Tailwind components that are generated by plugins */
/**
 * @import here any custom CSS components - that is, classes that
 * you'd want loaded before the Tailwind utilities, so the
 * utilities can still override them.
*/
/* Tailwind utility classes */
.m-0 {
  margin: 0 !important
}
.my-3 {
  margin-top: 3px !important;
  margin-bottom: 3px !important
}
.my-4 {
  margin-top: 4px !important;
  margin-bottom: 4px !important
}
.mt-6 {
  margin-top: 6px !important
}
.mt-10 {
  margin-top: 10px !important
}
.mb-16 {
  margin-bottom: 16px !important
}
.mb-4 {
  margin-bottom: 4px !important
}
.mb-24 {
  margin-bottom: 24px !important
}
.block {
  display: block !important
}
.inline-block {
  display: inline-block !important
}
.flex {
  display: flex !important
}
.table {
  display: table !important
}
.hidden {
  display: none !important
}
.h-4 {
  height: 4px !important
}
.h-px {
  height: 1px !important
}
.h-5 {
  height: 5px !important
}
.h-32 {
  height: 32px !important
}
.h-64 {
  height: 64px !important
}
.h-48 {
  height: 48px !important
}
.min-h-screen {
  min-height: 100vw !important
}
.w-4 {
  width: 4px !important
}
.w-full {
  width: 100% !important
}
.w-14 {
  width: 14px !important
}
.w-5 {
  width: 5px !important
}
.w-600 {
  width: 600px !important
}
.w-48 {
  width: 48px !important
}
.w-1\/2 {
  width: 50% !important
}
.cursor-default {
  cursor: default !important
}
.flex-col {
  flex-direction: column !important
}
.items-center {
  align-items: center !important
}
.justify-center {
  justify-content: center !important
}
.justify-between {
  justify-content: space-between !important
}
.space-y-5 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(5px * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(5px * var(--tw-space-y-reverse)) !important
}
.space-y-1 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(0.25rem * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(0.25rem * var(--tw-space-y-reverse)) !important
}
.space-x-2 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-x-reverse: 0 !important;
  margin-right: calc(2px * var(--tw-space-x-reverse)) !important;
  margin-left: calc(2px * calc(1 - var(--tw-space-x-reverse))) !important
}
.space-y-4 > :not([hidden]) ~ :not([hidden]) {
  --tw-space-y-reverse: 0 !important;
  margin-top: calc(4px * calc(1 - var(--tw-space-y-reverse))) !important;
  margin-bottom: calc(4px * var(--tw-space-y-reverse)) !important
}
.overflow-hidden {
  overflow: hidden !important
}
.rounded-md {
  border-radius: 6px !important
}
.rounded {
  border-radius: 4px !important
}
.border {
  border-width: 1px !important
}
.border-gray-300 {
  border-color: #d1d5db !important
}
.border-gray-800 {
  border-color: #1f2937 !important
}
.border-blue-500 {
  border-color: #3b82f6 !important
}
.bg-gray-100 {
  background-color: #f3f4f6 !important
}
.bg-white {
  background-color: #ffffff !important
}
.bg-blue-500 {
  background-color: #3b82f6 !important
}
.bg-gray-400 {
  background-color: #9ca3af !important
}
.bg-indigo-800 {
  background-color: #3730a3 !important
}
.bg-gray-300 {
  background-color: #d1d5db !important
}
.bg-gray-200 {
  background-color: #e5e7eb !important
}
.bg-cover {
  background-size: cover !important
}
.bg-top {
  background-position: top !important
}
.bg-no-repeat {
  background-repeat: no-repeat !important
}
.fill-current {
  fill: currentColor !important
}
.p-1 {
  padding: 0.25rem !important
}
.p-4 {
  padding: 4px !important
}
.p-5 {
  padding: 5px !important
}
.p-48 {
  padding: 48px !important
}
.p-24 {
  padding: 24px !important
}
.py-6 {
  padding-top: 6px !important;
  padding-bottom: 6px !important
}
.px-4 {
  padding-left: 4px !important;
  padding-right: 4px !important
}
.py-2 {
  padding-top: 2px !important;
  padding-bottom: 2px !important
}
.py-16 {
  padding-top: 16px !important;
  padding-bottom: 16px !important
}
.px-24 {
  padding-left: 24px !important;
  padding-right: 24px !important
}
.px-48 {
  padding-left: 48px !important;
  padding-right: 48px !important
}
.py-24 {
  padding-top: 24px !important;
  padding-bottom: 24px !important
}
.py-32 {
  padding-top: 32px !important;
  padding-bottom: 32px !important
}
.pb-32 {
  padding-bottom: 32px !important
}
.pr-16 {
  padding-right: 16px !important
}
.pl-16 {
  padding-left: 16px !important
}
.text-left {
  text-align: left !important
}
.text-center {
  text-align: center !important
}
.font-sans {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important
}
.text-4xl {
  font-size: 36px !important
}
.text-sm {
  font-size: 14px !important
}
.text-2xl {
  font-size: 24px !important
}
.text-lg {
  font-size: 18px !important
}
.text-base {
  font-size: 16px !important
}
.text-xl {
  font-size: 20px !important
}
.text-xs {
  font-size: 12px !important
}
.font-bold {
  font-weight: 700 !important
}
.font-normal {
  font-weight: 400 !important
}
.font-semibold {
  font-weight: 600 !important
}
.font-medium {
  font-weight: 500 !important
}
.uppercase {
  text-transform: uppercase !important
}
.italic {
  font-style: italic !important
}
.leading-64 {
  line-height: 64px !important
}
.leading-24 {
  line-height: 24px !important
}
.leading-full {
  line-height: 100% !important
}
.leading-px {
  line-height: 1px !important
}
.tracking-wider {
  letter-spacing: 0.05em !important
}
.text-white {
  color: #ffffff !important
}
.text-gray-300 {
  color: #d1d5db !important
}
.text-gray-700 {
  color: #374151 !important
}
.text-gray-500 {
  color: #6b7280 !important
}
.text-blue-600 {
  color: #2563eb !important
}
.text-gray-800 {
  color: #1f2937 !important
}
.text-blue-500 {
  color: #3b82f6 !important
}
.text-gray-600 {
  color: #4b5563 !important
}
.underline {
  text-decoration: underline !important
}
.no-underline {
  text-decoration: none !important
}
.transition {
  transition-property: background-color, border-color, color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter !important;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1) !important;
  transition-duration: 150ms !important
}
.transition-colors {
  transition-property: background-color, border-color, color, fill, stroke !important;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1) !important;
  transition-duration: 150ms !important
}
.duration-300 {
  transition-duration: 300ms !important
}
.shadow {
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06) !important
}
.shadow-lg {
  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05) !important
}
/* Your custom utility classes */
/*
 * Here is where you can define your custom utility classes.
 *
 * We wrap them in the `utilities` @layer directive, so
 * that Tailwind moves them to the correct location.
 *
 * More info:
 * https://tailwindcss.com/docs/functions-and-directives#layer
*/
.hover\:bg-blue-600:hover {
  background-color: #2563eb !important
}
.hover\:bg-gray-800:hover {
  background-color: #1f2937 !important
}
.hover\:bg-blue-500:hover {
  background-color: #3b82f6 !important
}
.hover\:bg-indigo-700:hover {
  background-color: #4338ca !important
}
.hover\:text-blue-400:hover {
  color: #60a5fa !important
}
.hover\:underline:hover {
  text-decoration: underline !important
}
.hover\:no-underline:hover {
  text-decoration: none !important
}
.focus\:border-transparent:focus {
  border-color: transparent !important
}
.focus\:text-blue-800:focus {
  color: #1e40af !important
}
.focus\:outline-none:focus {
  outline: 2px solid transparent !important;
  outline-offset: 2px !important
}
.focus\:ring-offset-0:focus {
  --tw-ring-offset-width: 0px !important
}
.group:hover .group-hover\:text-white {
  color: #ffffff !important
}
@media (max-width: 600px) {
  .sm\:inline-block {
    display: inline-block !important
  }
  .sm\:h-32 {
    height: 32px !important
  }
  .sm\:w-full {
    width: 100% !important
  }
  .sm\:w-16 {
    width: 16px !important
  }
  .sm\:px-16 {
    padding-left: 16px !important;
    padding-right: 16px !important
  }
  .sm\:py-32 {
    padding-top: 32px !important;
    padding-bottom: 32px !important
  }
  .sm\:px-24 {
    padding-left: 24px !important;
    padding-right: 24px !important
  }
  .sm\:px-0 {
    padding-left: 0 !important;
    padding-right: 0 !important
  }
  .sm\:pb-32 {
    padding-bottom: 32px !important
  }
  .sm\:leading-40 {
    line-height: 40px !important
  }
  .sm\:leading-32 {
    line-height: 32px !important
  }
}
</style>

</head>
<body class="bg-gray-100">

    <div class="hidden">We are glad to see your interest in our products. We will keep you posted on the latest&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; </div>
  <div role="article" aria-roledescription="email" aria-label="Welcome Aboard" lang="en">

    <table class="w-full font-sans" cellpadding="0" cellspacing="0" role="presentation">
      <tr>
        <td align="center" class="bg-gray-100">
          <table class="w-600 sm:w-full" cellpadding="0" cellspacing="0" role="presentation">
            <tr>
              <td class="p-48 sm:py-32 sm:px-24 text-center">
                <a target="_blank" href="malakoff.co">
                  <img src="https://malakoff.co/images/logo-color.svg" width="75" alt="Malakoff Analytics">
                </a>
              </td>
            </tr>
            <tr>
              <td align="center" class="sm:px-24">
                <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                  <tr>
                    <td class="bg-white text-gray-800 text-base text-left p-48 sm:px-24 leading-24 rounded">
                      <p>Hello there,</p>
                      <p class="text-2xl sm:leading-32 text-gray-700 font-semibold m-0 mb-24">Thanks for joning our subscriber list 🎊</p>
                      <p class="m-0 mb-24">We are glad to see your interest in our products. We will keep you posted on the latest</p>

                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="py-32">
                            <div class="bg-gray-200 h-px leading-px">&zwnj;</div>
                          </td>
                        </tr>
                      </table>
                      <small class="m-0 mb-16">Not sure why you received this email? Please <a href="mailto:info@malakoffanalytics.co.ke"
                                                                                           class="text-blue-500 underline
                                                                                           hover:no-underline">let us know</a>.</small>
                      <small class="m-0 mb-16">Thanks, <br>The Malakoff Team</small>
                    </td>
                  </tr>
                  <tr>
                    <td class="h-48"></td>
                  </tr>
                  <tr>
                    <td class="text-center text-gray-600 text-xs px-24">
                      <p class="m-0 mb-4 uppercase">&copy; Malakoff Analytics 2022</p>
                      <p class="m-0 italic">Speed, Convenience, and Accessibility</p>
                      <p class="cursor-default">
                        <a href="www.malakoffanalytics.co.ke" class="text-blue-500 no-underline hover:underline">Site</a> &bull;
                        <a href="#_" class="text-blue-500 no-underline hover:underline">Products</a> &bull;
                        <a href="#_" class="text-blue-500 no-underline hover:underline">Legal</a>
                      </p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

  </div>
</body>
</html>
